import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
// import Opening from "@/components/Opening";
import SplashScreen from "@/components/SplashScreen";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "About Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="snap-y snap-mandatory scroll-smooth">
      <body 
        className={`min-h-[100vh] relative ${inter.className}`}
      >
        {/* <SplashScreen> */}
          <Navbar />
          {children}
        {/* </SplashScreen> */}
        <Footer />
      </body>
    </html>
  );
}
