import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import Opening from "@/components/Opening";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "About Me",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-b from-white to-red-100 min-h-[100vh] relative ${inter.className}`}
      >
        <Opening />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
